# SPDX-FileCopyrightText: Enno Hermann
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "ko_speech_tools"
SPDX-PackageSupplier = "Enno Hermann <enno.hermann@gmail.com>"

[[annotations]]
path = [".python-version", "uv.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Enno Hermann"
SPDX-License-Identifier = "CC0-1.0"
