# SPDX-FileCopyrightText: Enno Hermann
#
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup uv
        uses: ./.github/actions/setup-uv
      - name: Tests
        run: uv run --all-extras coverage run --parallel
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: coverage-data-${{ matrix.os }}-${{ matrix.python-version }}
          path: .coverage.*
          if-no-files-found: ignore
  coverage:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup uv
        uses: ./.github/actions/setup-uv
      - uses: actions/download-artifact@v5
        with:
          pattern: coverage-data-*
          merge-multiple: true
      - name: Combine coverage
        run: |
          uvx coverage combine
          uvx coverage html --skip-covered --skip-empty
          uvx coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
